//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TobeLibraryDataAccess
{
    using LibraryEntities;
    using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;

    public partial class LibraryContext : DbContext
    {
        public LibraryContext() : base("MyDataModelContainer")
        {
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Drawers> Drawers { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BorrowedBooks> BorrowedBooks { get; set; }
        public virtual DbSet<Administrators> Administrators { get; set; }
    }
}
